version: '3.9'

networks:
  mlflow:
    driver: bridge

services:
  minio:
    image: minio/minio
    container_name: minio_s3
    command: server /data --console-address :9001
#    ports:
#      - "127.0.0.1:9000:9000"
#      - "127.0.0.1:9001:9001"
    expose:
      - "9000"
      - "9001"
    networks:
      - mlflow
    volumes:
      - ./minio/data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - mlflow
    depends_on:
      - minio

  api:
    build: mlops_lapiml
    image: mlops_lapiml
    container_name: mlops_lapiml
    restart: always
    depends_on:
      - minio
    networks:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://nginx:9000
    ports:
      - "7777:6755"
      - "127.0.0.1:8080:8080"
#    volumes:
#      - ./src:/app/src
#      - ./flaskapi.py:/app/flaskapi.py
#      - ./init.sh:/app/init.sh
    env_file:
      - ./.env

  ftpd_server:
    image: stilliard/pure-ftpd:latest
    container_name: ftpd_server
    environment:
      - PUBLICHOST=${HOST_IP}
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      - mlflow
    volumes:
      - .\DockerData\volumes\ftp:/home/ftpusers
    env_file:
      - ./.env

  mlflow:
    build: mlflow
    image: mlflow:latest
    container_name: mlflow
    networks:
      - mlflow
    environment:
      - ARTIFACT_ROOT=ftp://mlflow:password@${HOST_IP}/data
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .\DockerData\volumes\mlflow:/app
    depends_on:
      - ftpd_server
    env_file:
      - ./.env