version: '3.9'

networks:
  mlflow:
    driver: bridge

services:
  minio:
    image: minio/minio
    container_name: minio_s3
    command: server /data --console-address :9001
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    networks:
      - mlflow
    volumes:
      - ./minio/data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file:
      - ./.env

  api:
    build: .
    image: mlops_lapiml
    container_name: mlops_lapiml
    restart: always
    depends_on:
      - minio
    networks:
      - mlflow
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - ./.env

  mlflow:
    build: mlflow
    image: mlflow:latest
    container_name: mlflow
    depends_on:
      - minio
    networks:
      - mlflow
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .\DockerData\volumes\mlflow:/app
    env_file:
      - ./.env