.DEFAULT_GOAL := help
TARGET = origin/master
SRC = src/*

define find.functions
	@grep -E '^[a-zA-Z0-9 -]+:.*#'  Makefile | sort | while read -r l; do printf "\033[1;32m$$(echo $$l | cut -f 1 -d':')\033[00m:$$(echo $$l | cut -f 2- -d'#')\n"; done
endef

help: 
	$(call find.functions)

leave: clean 
	deactivate

clean: 
	rm -rf __pycache__ .mypy_cache .ruff_cache

lint: 
	ruff check --exit-zero $(SRC)
	darker --revision $(TARGET) --diff --check $(SRC)

lint-path: 
	ruff check --exit-zero $(path)
	darker --revision $(TARGET) --diff --check $(path)

format: 
	ruff --fix --silent --exit-zero $(SRC)
	darker --revision $(TARGET) $(SRC)

format-path: 
	ruff --fix --silent --exit-zero $(path)
	darker --revision $(TARGET) $(path)

typecheck: 
	mypy src/*.py

typecheck-path: 
	mypy $(path)

security-check: 
	bandit $(SRC)

run-app: 
	sh init.sh

run-tests: 
	python run pytest tests

.PHONY: help clean leave lint lint-path format format-path typecheck typecheck-path security-check run-app run-tests

